# Generated by Django 4.1.6 on 2023-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=10)),
                ("Lastname", models.CharField(max_length=10)),
                ("emp_id", models.IntegerField()),
            ],
        ),
    ]
